package Private;

import org.testng.annotations.Test;
import org.testng.Assert;
import java.io.IOException;
import java.sql.SQLException;

import org.testng.annotations.Test;
import org.testng.Assert;

import com.NexustAPIAutomation.java.CommonMethods;

//import freemarker.core.BugException;

public class SmartyStreetValidationV4  extends BaseClass{

	
	@Test(priority = 1, groups = "Smarty")
	public void postvalidateAddresses() throws ClassNotFoundException, SQLException, InterruptedException, IOException {
		// Still Bug (2025)
		// CommonMethods.Bug("CPDEV-21907");
		String uri = "/customers/validateAddresses";
		String ver = "4.0";
		String payload = "{\r\n" + "       \"Address\": [\r\n" + "        {\r\n"
				+ "            \"AddressId\": \"\",\r\n" + "            \"AddressCode\": \"PRIMARY\",\r\n"
				+ "            \"ContactPerson\": \"\",\r\n" + "            \"AddressLabel\":{\r\n"
				+ "                \"Line1\":\"1119 skylino DR\",\r\n" + "                \"Line2\":\"\",\r\n"
				+ "                \"City\":\"Griffin\",\r\n" + "                \"State\":\"GA\",\r\n"
				+ "                \"ZipCode\":\"302824\",\r\n" + "                \"Country\":\"USA\",\r\n"
				+ "                \"IsDirty\":false\r\n" + "            },\r\n"
				+ "            \"BillToAddress\": false,\r\n" + "            \"Override\": {\r\n"
				+ "                \"Override\": false,\r\n" + "                \"AddressCode\": \"\",\r\n"
				+ "                \"FromDate\": \"1900-01-01\",\r\n"
				+ "                \"ToDate\": \"1900-01-01\",\r\n" + "                \"Recurring\": false\r\n"
				+ "            },\r\n" + "            \"PhoneNumber\": [\r\n" + "                {\r\n"
				+ "                    \"Number\": \"\",\r\n" + "                    \"TypeId\": 0,\r\n"
				+ "                    \"Description\": \"empty\",\r\n" + "                    \"IsDirty\": false\r\n"
				+ "                }\r\n" + "            ],\r\n" + "            \"FaxNumber\": {\r\n"
				+ "                \"Number\": \"\",\r\n" + "                \"IsDirty\": false\r\n"
				+ "            }\r\n" + "        }\r\n" + "    ]\r\n" + "}\r\n" + " ";
		String expected = "{ \"ValidateAddresses\": {\"Success\":true,\"Data\":{\"AddressId\":\"\",\"AddressCode\":\"PRIMARY\",\"ContactPerson\":\"\",\"AddressLabel\":{\"Line1\":\"1119 skylino DR\",\"Line2\":\"\",\"City\":\"Griffin\",\"State\":\"GA\",\"ZipCode\":\"302824\",\"Country\":\"USA\",\"IsDirty\":false},\"BillToAddress\":false,\"Override\":{\"Override\":false,\"AddressCode\":\"\",\"FromDate\":\"1900-01-01\",\"ToDate\":\"1900-01-01\",\"Recurring\":false},\"PhoneNumber\":[{\"Number\":\"\",\"TypeId\":0,\"Description\":\"empty\",\"IsDirty\":false}],\"FaxNumber\":{\"Number\":\"\",\"IsDirty\":false},\"SmartyStreetsMailingAddressCandidate\":{\"AddressId\":\"\",\"DeliveryLine1\":\"1119 Skyline Dr\",\"DeliveryLine2\":\"\",\"LastLine\":\"Griffin GA 30224-4958\",\"StreetNumber\":\"1119\",\"StreetNumberLng\":1119,\"StrNumberSuffix\":\"\",\"StreetName\":\"Skyline\",\"StreetType\":\"Dr\",\"StreetDirectionP\":\"\",\"StreetDirection\":\"\",\"AptNumber\":\"\",\"AptDescription\":\"\",\"UnitDesignation\":\"\",\"AptNumberPlus\":\"\",\"CityName\":\"Griffin\",\"State\":\"GA\",\"ZipCode\":\"30224\",\"Plus4Code\":\"4958\",\"Country\":\"USA\",\"Success\":true,\"MailingAddressMessages\":{\"Messages\":[{\"Enabled\":1,\"Info\":\"Confirmed; entire address was Delivery Point Validation confirmed deliverable.\",\"AddressCode\":\"\"},{\"Enabled\":1,\"Info\":\"City/state/ZIP + street are all valid.\",\"AddressCode\":\"\"},{\"Enabled\":1,\"Info\":\"ZIP+4 matched; confirmed entire address; address is valid.\",\"AddressCode\":\"\"}]}}},\"Messages\":[]}}";
		CommonMethods.postMethodString(payload, uri, ver, expected);

	Thread.sleep(2000);

	}

	@Test(priority = 2, groups = "Smarty")
	public void postvalidLocation() throws ClassNotFoundException, SQLException, InterruptedException, IOException {
		// Still Bug (2025)
		// CommonMethods.Bug("CPDEV-21907");
		String uri = "/location";
		String ver = "4.0";
		String payload = "{\r\n"
				+ "   \"LocationId\":\"2027\",\r\n"
				+ "    \"Description\":\"\",\r\n"
				+ "    \"LocationClassId\":\"\",\r\n"
				+ "    \"BillToCustomerId\":\"CUSTOMER013\",\r\n"
				+ "    \"ZoneId\":\"\",\r\n"
				+ "    \"Address\":\r\n"
				+ "    {\r\n"
				+ "        \"AddressId\": \"\",\r\n"
				+ "        \"AddressCode\":\"PRIMARY\",\r\n"
				+ "        \"AddressLabel\":{\r\n"
				+ "                \"Line1\":\"22 Degroat Rd\",\r\n"
				+ "                \"Line2\":\"Building 15000\",\r\n"
				+ "                \"City\":\"\",\r\n"
				+ "                \"State\":\"NJ\",\r\n"
				+ "                \"ZipCode\":\"07827\",\r\n"
				+ "                \"Country\":\"USA\",\r\n"
				+ "                \"IsDirty\":true\r\n"
				+ "        },\r\n"
				+ "              \"SmartyStreetsMailingAddressCandidate\": {\r\n"
				+ "                \"AddressId\": \"\",\r\n"
				+ "                \"DeliveryLine1\": \"1119 Skyline Dr\",\r\n"
				+ "                \"DeliveryLine2\": \"\",\r\n"
				+ "                \"LastLine\": \"Griffin GA 30224-4958\",\r\n"
				+ "                \"StreetNumber\": \"1119\",\r\n"
				+ "                \"StreetNumberLng\": 1119,\r\n"
				+ "                \"StrNumberSuffix\": \"\",\r\n"
				+ "                \"StreetName\": \"Skyline\",\r\n"
				+ "                \"StreetType\": \"Dr\",\r\n"
				+ "                \"StreetDirectionP\": \"\",\r\n"
				+ "                \"StreetDirection\": \"\",\r\n"
				+ "                \"AptNumber\": \"\",\r\n"
				+ "                \"AptDescription\": \"\",\r\n"
				+ "                \"UnitDesignation\": \"\",\r\n"
				+ "                \"AptNumberPlus\": \"\",\r\n"
				+ "                \"CityName\": \"Griffin\",\r\n"
				+ "                \"State\": \"GA\",\r\n"
				+ "                \"ZipCode\": \"30224\",\r\n"
				+ "                \"Plus4Code\": \"4958\",\r\n"
				+ "                \"Country\": \"USA\",\r\n"
				+ "                \"Success\": true\r\n"
				+ " \r\n"
				+ "                }\r\n"
				+ "        },\r\n"
				+ "    \"Billing\":{\r\n"
				+ "        \"AccumulatedBilling\":{\r\n"
				+ "            \"Type\":1,\r\n"
				+ "            \"MasterId\":\"\"\r\n"
				+ "        },\r\n"
				+ "        \"Transfer\":{\r\n"
				+ "            \"AllowTransferWithoutFinalBill\":true,\r\n"
				+ "            \"MoveBalanceOnTransfer\":0\r\n"
				+ "        },\r\n"
				+ "        \"DefaultRouteId\":\"R123\",\r\n"
				+ "        \"FinalReadRouteId\":\"FR123\",\r\n"
				+ "        \"BillingCycle\":{\r\n"
				+ "            \"Override\":true,\r\n"
				+ "            \"Id\":\"MONTHLY\"\r\n"
				+ "        },\r\n"
				+ "        \"LocationPaymentTermId\":\"PT123\",\r\n"
				+ "        \"PaymentTermOverrideId\":\"PTO123\",\r\n"
				+ "        \"HDDZoneId\":\"HDD123\",\r\n"
				+ "        \"AllowMinimumBill\":true,\r\n"
				+ "        \"AllowMaximumBill\":true,\r\n"
				+ "        \"ItemizedStatement\":true,\r\n"
				+ "        \"NumberOfBillCopies\":1,\r\n"
				+ "        \"AccumulateAccessEnergy\":true,\r\n"
				+ "        \"EligibleForRecall\":true\r\n"
				+ "    },\r\n"
				+ "    \"CustomerOptions\":{\r\n"
				+ "        \"Customer1Id\":\"\",\r\n"
				+ "        \"Customer2Id\":\"\",\r\n"
				+ "        \"Customer3Id\":\"\",\r\n"
				+ "        \"DefaultMoveIn\":{\r\n"
				+ "            \"Enabled\":true,\r\n"
				+ "            \"CustomerMoveInId\": 1,\r\n"
				+ "            \"TaxScheduleId\": \"\"\r\n"
				+ "        }\r\n"
				+ "    },\r\n"
				+ "    \"LocationOptions\":{\r\n"
				+ "        \"AssessorId\":\"\",\r\n"
				+ "        \"PlanNumber\":\"\",\r\n"
				+ "        \"KeyNumber\":\"\",\r\n"
				+ "        \"SICCode\":\"S123\",\r\n"
				+ "        \"LotNumber\":\"L123\",\r\n"
				+ "        \"NumberOfResidentialUnits\":10,\r\n"
				+ "        \"RevenueDistrictId\":\"RD123\",\r\n"
				+ "        \"ReceiptPoint\":0,\r\n"
				+ "        \"GISCoordinates\":{\r\n"
				+ "            \"X\":\"X123\",\r\n"
				+ "            \"Y\":\"Y123\"\r\n"
				+ "        },\r\n"
				+ "        \"ExcludeFromArchiving\":true,\r\n"
				+ "        \"PrepayStatus\":true\r\n"
				+ "    },\r\n"
				+ "    \"CollectionsOptions\":{\r\n"
				+ "        \"CurrentCustomerCollectionType\":\"CURRENT\",\r\n"
				+ "        \"FormerCustomerCollectionType\":\"FORMER\",\r\n"
				+ "        \"BudgetCustomerCollectionType\":\"BUDGET\",\r\n"
				+ "        \"SpaCustomerCollectionType\":\"\",\r\n"
				+ "        \"DisconnectExempt\":{\r\n"
				+ "            \"ExemptType\":\"SPECIAL STATUS\",\r\n"
				+ "            \"EffectiveStartDate\":\"2023-01-01\",\r\n"
				+ "            \"EffectiveEndDate\":\"2023-12-31\",\r\n"
				+ "            \"Reoccurring\":true\r\n"
				+ "        },\r\n"
				+ "         \"PenaltyExempt\":{\r\n"
				+ "            \"Enabled\": false,\r\n"
				+ "            \"ExemptType\":\"\",\r\n"
				+ "            \"EffectiveStartDate\":\"1900-01-01\",\r\n"
				+ "            \"EffectiveEndDate\":\"1900-12-31\"\r\n"
				+ "        },\r\n"
				+ "        \"NoExtension\":true\r\n"
				+ "    },\r\n"
				+ "    \"ServiceOptions\":{\r\n"
				+ "        \"Service\":[\r\n"
				+ "            {\r\n"
				+ "                \"CategoryId\":1,\r\n"
				+ "                \"Estimate\":true,\r\n"
				+ "                \"PenaltyId\":\"5%\",\r\n"
				+ "                \"AccountReceivableIndex\":1,\r\n"
				+ "                \"TaxScheduleId\":\"\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"CategoryId\":2,\r\n"
				+ "                \"Estimate\":true,\r\n"
				+ "                \"PenaltyId\":\"5%\",\r\n"
				+ "                \"AccountReceivableIndex\":1,\r\n"
				+ "                \"TaxScheduleId\":\"\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"CategoryId\":3,\r\n"
				+ "                \"Estimate\":false,\r\n"
				+ "                \"PenaltyId\":\"5%\",\r\n"
				+ "                \"AccountReceivableIndex\":1,\r\n"
				+ "                \"TaxScheduleId\":\"\"\r\n"
				+ "            },\r\n"
				+ "                {\r\n"
				+ "                \"CategoryId\":4,\r\n"
				+ "                \"Estimate\":true,\r\n"
				+ "                \"PenaltyId\":\"5%\",\r\n"
				+ "                \"AccountReceivableIndex\":1,\r\n"
				+ "                \"TaxScheduleId\":\"\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"CategoryId\":5,\r\n"
				+ "                \"Estimate\":true,\r\n"
				+ "                \"PenaltyId\":\"5%\",\r\n"
				+ "                \"AccountReceivableIndex\":1,\r\n"
				+ "                \"TaxScheduleId\":\"\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"CategoryId\":6,\r\n"
				+ "                \"Estimate\":false,\r\n"
				+ "                \"PenaltyId\":\"5%\",\r\n"
				+ "                \"AccountReceivableIndex\":1,\r\n"
				+ "                \"TaxScheduleId\":\"\"\r\n"
				+ "            }\r\n"
				+ "        ]\r\n"
				+ "    },\r\n"
				+ "    \"AddressConfirm\":true,\r\n"
				+ "    \"Confirm\":true\r\n"
				+ "}\r\n"
				+ " ";

		String expected = "{\"Location\":{\"Success\":true,\"Data\":null,\"Messages\":[{\"Enabled\":1,\"Info\":\"Location created successfully\",\"Level\":1}]}}";
		//CommonMethods.putMethodstring(uri, ver, payload, expected);
		CommonMethods.postMethodString(payload, uri, ver, expected);

	}


	@Test(priority = 3, groups = "Smarty")
	public void putvalidLocation() throws ClassNotFoundException, SQLException, InterruptedException, IOException {
		// Still Bug (2025)
		// CommonMethods.Bug("CPDEV-21907");
		String uri = "/location";
		String ver = "4.0";
		String payload = "{\r\n"
				+ "   \"LocationId\":\"2027\",\r\n"
				+ "    \"Description\":\"\",\r\n"
				+ "    \"LocationClassId\":\"\",\r\n"
				+ "    \"BillToCustomerId\":\"CUSTOMER013\",\r\n"
				+ "    \"ZoneId\":\"\",\r\n"
				+ "    \"Address\":\r\n"
				+ "    {\r\n"
				+ "        \"AddressId\": \"267\",\r\n"
				+ "        \"AddressCode\":\"PRIMARY\",\r\n"
				+ "        \"AddressLabel\":{\r\n"
				+ "                \"Line1\":\"220 Degroat Rd\",\r\n"
				+ "                \"Line2\":\"Building 16000\",\r\n"
				+ "                \"City\":\"\",\r\n"
				+ "                \"State\":\"NJ\",\r\n"
				+ "                \"ZipCode\":\"07827\",\r\n"
				+ "                \"Country\":\"USA\",\r\n"
				+ "                \"IsDirty\":true\r\n"
				+ "        },\r\n"
				+ "              \"SmartyStreetsMailingAddressCandidate\": {\r\n"
				+ "                \"AddressId\": \"\",\r\n"
				+ "                \"DeliveryLine1\": \"1119 Skyline Dr\",\r\n"
				+ "                \"DeliveryLine2\": \"\",\r\n"
				+ "                \"LastLine\": \"Griffin GA 30224-4958\",\r\n"
				+ "                \"StreetNumber\": \"1119\",\r\n"
				+ "                \"StreetNumberLng\": 1119,\r\n"
				+ "                \"StrNumberSuffix\": \"\",\r\n"
				+ "                \"StreetName\": \"Skyline\",\r\n"
				+ "                \"StreetType\": \"Dr\",\r\n"
				+ "                \"StreetDirectionP\": \"\",\r\n"
				+ "                \"StreetDirection\": \"\",\r\n"
				+ "                \"AptNumber\": \"\",\r\n"
				+ "                \"AptDescription\": \"\",\r\n"
				+ "                \"UnitDesignation\": \"\",\r\n"
				+ "                \"AptNumberPlus\": \"\",\r\n"
				+ "                \"CityName\": \"Griffin\",\r\n"
				+ "                \"State\": \"GA\",\r\n"
				+ "                \"ZipCode\": \"30224\",\r\n"
				+ "                \"Plus4Code\": \"4958\",\r\n"
				+ "                \"Country\": \"USA\",\r\n"
				+ "                \"Success\": true\r\n"
				+ " \r\n"
				+ "                }\r\n"
				+ "        },\r\n"
				+ "    \"Billing\":{\r\n"
				+ "        \"AccumulatedBilling\":{\r\n"
				+ "            \"Type\":1,\r\n"
				+ "            \"MasterId\":\"\"\r\n"
				+ "        },\r\n"
				+ "        \"Transfer\":{\r\n"
				+ "            \"AllowTransferWithoutFinalBill\":true,\r\n"
				+ "            \"MoveBalanceOnTransfer\":0\r\n"
				+ "        },\r\n"
				+ "        \"DefaultRouteId\":\"R123\",\r\n"
				+ "        \"FinalReadRouteId\":\"FR123\",\r\n"
				+ "        \"BillingCycle\":{\r\n"
				+ "            \"Override\":true,\r\n"
				+ "            \"Id\":\"MONTHLY\"\r\n"
				+ "        },\r\n"
				+ "        \"LocationPaymentTermId\":\"PT123\",\r\n"
				+ "        \"PaymentTermOverrideId\":\"PTO123\",\r\n"
				+ "        \"HDDZoneId\":\"HDD123\",\r\n"
				+ "        \"AllowMinimumBill\":true,\r\n"
				+ "        \"AllowMaximumBill\":true,\r\n"
				+ "        \"ItemizedStatement\":true,\r\n"
				+ "        \"NumberOfBillCopies\":1,\r\n"
				+ "        \"AccumulateAccessEnergy\":true,\r\n"
				+ "        \"EligibleForRecall\":true\r\n"
				+ "    },\r\n"
				+ "    \"CustomerOptions\":{\r\n"
				+ "        \"Customer1Id\":\"\",\r\n"
				+ "        \"Customer2Id\":\"\",\r\n"
				+ "        \"Customer3Id\":\"\",\r\n"
				+ "        \"DefaultMoveIn\":{\r\n"
				+ "            \"Enabled\":true,\r\n"
				+ "            \"CustomerMoveInId\": 1,\r\n"
				+ "            \"TaxScheduleId\": \"\"\r\n"
				+ "        }\r\n"
				+ "    },\r\n"
				+ "    \"LocationOptions\":{\r\n"
				+ "        \"AssessorId\":\"\",\r\n"
				+ "        \"PlanNumber\":\"\",\r\n"
				+ "        \"KeyNumber\":\"\",\r\n"
				+ "        \"SICCode\":\"S123\",\r\n"
				+ "        \"LotNumber\":\"L123\",\r\n"
				+ "        \"NumberOfResidentialUnits\":10,\r\n"
				+ "        \"RevenueDistrictId\":\"RD123\",\r\n"
				+ "        \"ReceiptPoint\":0,\r\n"
				+ "        \"GISCoordinates\":{\r\n"
				+ "            \"X\":\"X123\",\r\n"
				+ "            \"Y\":\"Y123\"\r\n"
				+ "        },\r\n"
				+ "        \"ExcludeFromArchiving\":true,\r\n"
				+ "        \"PrepayStatus\":true\r\n"
				+ "    },\r\n"
				+ "    \"CollectionsOptions\":{\r\n"
				+ "        \"CurrentCustomerCollectionType\":\"CURRENT\",\r\n"
				+ "        \"FormerCustomerCollectionType\":\"FORMER\",\r\n"
				+ "        \"BudgetCustomerCollectionType\":\"BUDGET\",\r\n"
				+ "        \"SpaCustomerCollectionType\":\"\",\r\n"
				+ "        \"DisconnectExempt\":{\r\n"
				+ "            \"ExemptType\":\"SPECIAL STATUS\",\r\n"
				+ "            \"EffectiveStartDate\":\"2023-01-01\",\r\n"
				+ "            \"EffectiveEndDate\":\"2023-12-31\",\r\n"
				+ "            \"Reoccurring\":true\r\n"
				+ "        },\r\n"
				+ "         \"PenaltyExempt\":{\r\n"
				+ "            \"Enabled\": false,\r\n"
				+ "            \"ExemptType\":\"\",\r\n"
				+ "            \"EffectiveStartDate\":\"1900-01-01\",\r\n"
				+ "            \"EffectiveEndDate\":\"1900-12-31\"\r\n"
				+ "        },\r\n"
				+ "        \"NoExtension\":true\r\n"
				+ "    },\r\n"
				+ "    \"ServiceOptions\":{\r\n"
				+ "        \"Service\":[\r\n"
				+ "            {\r\n"
				+ "                \"CategoryId\":1,\r\n"
				+ "                \"Estimate\":true,\r\n"
				+ "                \"PenaltyId\":\"5%\",\r\n"
				+ "                \"AccountReceivableIndex\":1,\r\n"
				+ "                \"TaxScheduleId\":\"\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"CategoryId\":2,\r\n"
				+ "                \"Estimate\":true,\r\n"
				+ "                \"PenaltyId\":\"5%\",\r\n"
				+ "                \"AccountReceivableIndex\":1,\r\n"
				+ "                \"TaxScheduleId\":\"\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"CategoryId\":3,\r\n"
				+ "                \"Estimate\":false,\r\n"
				+ "                \"PenaltyId\":\"5%\",\r\n"
				+ "                \"AccountReceivableIndex\":1,\r\n"
				+ "                \"TaxScheduleId\":\"\"\r\n"
				+ "            },\r\n"
				+ "                {\r\n"
				+ "                \"CategoryId\":4,\r\n"
				+ "                \"Estimate\":true,\r\n"
				+ "                \"PenaltyId\":\"5%\",\r\n"
				+ "                \"AccountReceivableIndex\":1,\r\n"
				+ "                \"TaxScheduleId\":\"\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"CategoryId\":5,\r\n"
				+ "                \"Estimate\":true,\r\n"
				+ "                \"PenaltyId\":\"5%\",\r\n"
				+ "                \"AccountReceivableIndex\":1,\r\n"
				+ "                \"TaxScheduleId\":\"\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"CategoryId\":6,\r\n"
				+ "                \"Estimate\":false,\r\n"
				+ "                \"PenaltyId\":\"5%\",\r\n"
				+ "                \"AccountReceivableIndex\":1,\r\n"
				+ "                \"TaxScheduleId\":\"\"\r\n"
				+ "            }\r\n"
				+ "        ]\r\n"
				+ "    },\r\n"
				+ "    \"AddressConfirm\":true,\r\n"
				+ "    \"Confirm\":true\r\n"
				+ "}\r\n"
				+ " ";

		String expected = "{\"Location\":{\"Success\":true,\"Data\":null,\"Messages\":[{\"Enabled\":1,\"Info\":\"Location updated successfully\",\"Level\":1}]}}";
		CommonMethods.putMethodstring(uri, ver, payload, expected);
	//	CommonMethods.postMethodString(payload, uri, ver, expected);

	}

}